import type { Response } from 'express';
import type { FileDownload } from './storage.service';

/**
 * Answers a download request: sends the browser to a signed address, or streams
 * the bytes as an attachment that can never render or be sniffed as HTML.
 * The filename is generated by the server, never taken from the upload.
 */
export function sendDownload(response: Response, download: FileDownload): void {
  if (download.kind === 'redirect') {
    response.redirect(302, download.url);
    return;
  }

  response.set({
    'Content-Type': download.contentType,
    'Content-Disposition': `attachment; filename="${download.filename}"`,
    'X-Content-Type-Options': 'nosniff',
    'Cache-Control': 'private, no-store',
  });
  download.stream.on('error', () => response.destroy());
  download.stream.pipe(response);
}
